/**
 * Czech word list
 * @type {Object}
 * @property {string[]} easy - Easy words
 * @property {string[]} medium - Medium words
 * @property {string[]} hard - Hard words
 * @readonly
 */
const czechWords = {
  easy: [
    "pes",
    "kočka",
    "auto",
    "dům",
    "káva",
    "kolo",
    "kniha",
    "hodiny",
    "dveře",
    "okno",
    "stůl",
    "židle",
    "koule",
    "stěna",
    "tráva",
    "les",
    "ryba",
    "houska",
    "klobása",
    "mrak",
    "déšť",
    "sníh",
    "voda",
    "vítr",
    "země",
    "strom",
    "květ",
    "hora",
    "řeka",
    "jezero",
    "moře",
    "pláž",
    "písek",
    "kámen",
    "zahrada",
    "pole",
    "cibule",
  ],
  medium: [
    "autobus",
    "příroda",
    "obrázek",
    "počítač",
    "univerzita",
    "telefon",
    "televize",
    "internet",
    "kancelář",
    "elektrárna",
    "světlo",
    "rozvoj",
    "historie",
    "projekt",
    "vysvětlení",
    "organizace",
    "dokument",
    "podnikání",
    "podpora",
    "odpověď",
    "komunikace",
    "technologie",
    "společnost",
    "vzdělání",
    "návrh",
    "implementace",
    "strategie",
    "trh",
    "základna",
    "výzkum",
    "inovace",
    "kvalita",
    "proces",
    "úspěch",
    "analýza",
    "kreativita",
    "motivace",
    "systém",
    "úroveň",
    "zaměstnanec",
    "manažer",
    "účet",
    "finance",
    "struktura",
    "produkt",
    "konkurence",
    "rozhodnutí",
    "efektivita",
    "akce",
    "pyramida",
  ],
  hard: [
    "nejednoznačný",
    "nevyvratitelný",
    "neznámý",
    "podstatný",
    "zajímavý",
    "úspěšný",
    "spokojený",
    "nebezpečný",
    "obtížný",
    "zodpovědný",
    "pravděpodobný",
    "neodpustitelný",
    "nepřekonatelný",
    "neodolatelný",
    "neporazitelný",
    "přesný",
    "důležitý",
    "zajímavý",
    "očekávaný",
    "nepochopitelný",
    "nenahraditelný",
    "nepochybný",
    "nezbytný",
    "nezvratný",
    "nevyzpytatelný",
    "nezměnitelný",
    "nezdolatelný",
    "nezkrotný",
    "nezdůvodnitelný",
    "nevděčný",
    "nenahraditelný",
    "nemilosrdný",
    "nemožný",
    "nesmrtelný",
    "nevyvratitelný",
    "neodpustitelný",
    "nevyzpytatelný",
    "nepřehlédnutelný",
    "nepříjemný",
    "nepříjemný",
    "nesmělý",
    "nesmělý",
    "nespokojený",
    "nestálý",
    "nestoudný",
    "nesvobodný",
    "nesvobodný",
    "neutěšený",
  ],
};

/**
 * English word list
 * @type {Object}
 * @property {string[]} easy - Easy words
 * @property {string[]} medium - Medium words
 * @property {string[]} hard - Hard words
 * @readonly
 */
const englishWords = {
  easy: [
    "cat",
    "dog",
    "car",
    "house",
    "book",
    "ball",
    "bird",
    "tree",
    "chair",
    "table",
    "door",
    "window",
    "apple",
    "banana",
    "phone",
    "clock",
    "key",
    "pen",
    "shoe",
    "hat",
    "bag",
    "cake",
    "desk",
    "lamp",
    "shirt",
    "pants",
    "socks",
    "flower",
    "river",
    "lake",
    "ocean",
    "mountain",
    "cloud",
    "sun",
    "moon",
    "star",
    "sky",
    "grass",
    "sand",
    "snow",
    "rain",
    "wind",
    "earth",
    "fire",
    "door",
    "window",
    "bird",
    "chair",
    "table",
    "book",
    "apple",
    "car",
    "tree",
    "house",
    "phone",
    "clock",
    "pen",
    "cake",
    "onion",
  ],
  medium: [
    "elephant",
    "giraffe",
    "crocodile",
    "rhinoceros",
    "hippopotamus",
    "alligator",
    "kangaroo",
    "octopus",
    "penguin",
    "unicorn",
    "dragon",
    "dinosaur",
    "mosquito",
    "butterfly",
    "hedgehog",
    "cheetah",
    "panther",
    "chameleon",
    "raccoon",
    "pangolin",
    "flamingo",
    "caterpillar",
    "hummingbird",
    "squirrel",
    "koala",
    "albatross",
    "narwhal",
    "platypus",
    "anteater",
    "lemur",
    "armadillo",
    "gazelle",
    "mongoose",
    "orangutan",
    "meerkat",
    "woodpecker",
    "porcupine",
    "toucan",
    "weasel",
    "wolverine",
    "lynx",
    "otter",
    "vulture",
    "walrus",
    "yak",
    "zebra",
    "buffalo",
    "cassowary",
    "eland",
    "fossa",
    "pyramid",
  ],
  hard: [
    "exaggeration",
    "incomprehensible",
    "unbelievable",
    "extraordinary",
    "inconvenience",
    "catastrophe",
    "complication",
    "discombobulate",
    "disconcerting",
    "misunderstanding",
    "irreplaceable",
    "impossibility",
    "incomprehensibility",
    "incomprehensibleness",
    "indescribable",
    "inquisitiveness",
    "discombobulation",
    "inconspicuousness",
    "inconsequentially",
    "inconsequentiality",
    "misinterpretation",
    "miscommunication",
    "discombobulated",
    "uncontrollability",
    "inconceivability",
    "inconsiderateness",
    "unquestionably",
    "disestablishment",
    "indiscriminately",
    "unpredictability",
    "unintelligibility",
    "indispensableness",
    "uncharacteristically",
    "unintelligibleness",
    "unaccountability",
    "incomprehensibly",
    "incomprehensiveness",
    "indefatigableness",
    "inappropriateness",
    "inconsiderateness",
    "unconstitutionally",
    "misunderstandable",
    "incomprehensively",
    "unintelligibility",
    "indiscriminately",
    "unpredictability",
    "unintelligibleness",
    "incomprehensibility",
  ],
};

/**
 * Get random word
 * @param {string} difficulty
 * @param {string} language
 * @returns {string}
 */
export const getRandomWord = (difficulty, language) => {
  let wordList;
  if (language === "cs") {
    wordList = czechWords;
  } else if (language === "en") {
    wordList = englishWords;
  } else {
    throw new Error("Invalid language");
  }

  let words;
  if (difficulty == 1) {
    words = wordList.easy;
  } else if (difficulty == 2) {
    words = wordList.medium;
  } else if (difficulty == 3) {
    words = wordList.hard;
  } else {
    throw new Error("Invalid difficulty");
  }

  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
};
