// Custom vocabulary fallback for Typing Test
// Grouped by length: short, normal, long

const customWords = {
  SHORT: ["cat", "dog", "sun", "car", "hat", "run", "box", "red", "cup", "pen", "map", "bat", "fox", "sky", "key", "jam", "web", "zip", "owl", "ice"],
  NORMAL: [
    "window",
    "garden",
    "pencil",
    "bottle",
    "orange",
    "planet",
    "rocket",
    "guitar",
    "school",
    "forest",
    "camera",
    "rabbit",
    "pillow",
    "bridge",
    "castle",
    "wallet",
    "button",
    "cookie",
    "dragon",
    "flower",
    "helmet",
    "island",
    "jungle",
    "kitten",
    "ladder",
    "mirror",
    "notebook",
    "octopus",
    "pirate",
    "quartz",
    "rocket",
    "saddle",
    "ticket",
    "umbrella",
    "violin",
    "wallet",
    "xylophone",
    "yogurt",
    "zebra",
  ],
  LONG: [
    "adventure",
    "beautiful",
    "celebration",
    "determination",
    "enthusiasm",
    "friendship",
    "generation",
    "happiness",
    "imagination",
    "journalist",
    "knowledge",
    "landscape",
    "motivation",
    "navigation",
    "opportunity",
    "partnership",
    "questionnaire",
    "relationship",
    "significant",
    "transformation",
    "understanding",
    "vocabulary",
    "wonderfully",
    "xenophobia",
    "yesterday",
    "zoologist",
    "appreciation",
    "background",
    "championship",
    "development",
    "environment",
    "foundation",
    "government",
    "headquarters",
    "information",
    "judgement",
    "leadership",
    "management",
    "negotiation",
    "organization",
  ],
};

window.customWords = customWords;
